/**
 * Generates the Phase 13 evidence documents from the running system.
 *
 * Every number in the four artefacts below is read from the same engines, registry and connectors
 * the product uses. Nothing is transcribed. A hand-written integration matrix or golden-truth table
 * is a claim about a system rather than a measurement of one, and this repository has already paid
 * for that distinction once.
 *
 * Writes:
 *   docs/ENTERPRISE_INTEGRATION_MATRIX.md
 *   docs/SOURCE_AUTHORITY_MATRIX.md
 *   docs/ASSISTANT_GOLDEN_TRUTH_RESULTS.md
 *   docs/INGESTION_VALIDATION_RESULTS.md
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  GatewayToolPort, NEW_CONVERSATION, askWithPlan, vocabularyFrom,
} from '@app';
import type { PlannerVocabulary, SourceRegistry } from '@app';
import { CONCEPT_LABEL, STATUS_MEANING } from '@contexts/integration';
import { DEMO_NOW, createDemoApi } from '../security/demo-api.js';
import { knowledgeDemo, syncFixtures } from '../fixtures/demo-knowledge.js';
import { GOLDEN_TRUTH, type GoldenCase } from './golden-truth.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS = join(HERE, '..', '..', 'docs');

const HEADER = (title: string, purpose: string): string => `# ${title}

> **DEMO — SYNTHETIC DATA.** Generated by \`npm run report:phase13\` from the running system on
> ${DEMO_NOW}. Every figure below is read from the engines, the registry and the connectors the
> product itself uses; nothing here is transcribed by hand.

${purpose}
`;

async function main(): Promise<void> {
  const api = createDemoApi();
  const login = await api.login('exec.cdo');
  if (login === undefined) throw new Error('demo login failed');
  const ctx = api.contextFor('usr-exec-cdo', login.sessionId);
  const authorised = (await api.policy.resolveScope(ctx.auth)).projectIds;
  const discovered = await vocabularyFrom({
    ctx, gateway: api.gateway, asOf: DEMO_NOW, authorisedProjectIds: authorised,
  });
  const vocabulary: PlannerVocabulary = { ...discovered, accounts: [], customers: [] };

  const demo = knowledgeDemo(authorised, discovered.projects[0]?.id ?? 'prj-001');
  await syncFixtures(demo.registry);
  const sowReceipt = demo.addAtlasSow();
  const supplemental = demo.addSupplementalFinancials();
  const bad = demo.addBadRows();
  const minutes = demo.addUnassociatedMinutes();

  const tools = new GatewayToolPort(ctx, api.gateway, DEMO_NOW, authorised, demo.registry);

  mkdirSync(DOCS, { recursive: true });

  // -------------------------------------------------------------------------
  // Enterprise integration matrix (§103)
  // -------------------------------------------------------------------------
  const connectorRows: string[] = [];
  for (const source of demo.registry.sourceList()) {
    const connector = demo.registry.connector(source.sourceId);
    const schema = connector === undefined ? null : await connector.discoverSchema();
    const health = connector === undefined ? null : await connector.healthCheck();
    const mapping = connector?.mapSchema() ?? null;
    const summary = demo.registry.sources().find((s) => s.sourceId === source.sourceId);
    const identityCoverage = connector === undefined
      ? 'n/a'
      : `${String(demo.identity.coverage(authorised).find(
        (c) => c.system === connector.provenance.system,
      )?.mapped ?? 0)} of ${String(authorised.length)} projects mapped`;

    connectorRows.push([
      `| ${source.displayName}`,
      source.domain.toLowerCase().replace(/_/g, ' '),
      source.kind === 'CONNECTOR' ? 'adapter + fixture' : source.kind.toLowerCase().replace(/_/g, ' '),
      source.isFixture ? '**FIXTURE**' : source.kind === 'CANONICAL' ? 'generated' : 'real upload',
      connector === undefined ? 'n/a' : 'none configured',
      schema === null ? 'n/a' : schema.discoveredFromLiveSystem ? 'YES' : '**NO**',
      identityCoverage,
      (connector?.suppliesConcepts ?? []).length === 0
        ? (summary?.recordCount ?? 0) > 0 ? 'uploaded fields' : '—'
        : String((connector?.suppliesConcepts ?? []).length),
      summary?.authority ?? '—',
      connector?.getLastSync().lastSuccessAt ?? source.lastUpdated ?? 'never',
      `${String(summary?.recordCount ?? 0)} records`,
      `${health?.detail ?? STATUS_MEANING[source.status]} |`,
    ].join(' | '));
  }

  writeFileSync(join(DOCS, 'ENTERPRISE_INTEGRATION_MATRIX.md'), `${HEADER(
    'Enterprise integration matrix',
    `## What "FIXTURE" means here, and why every row says it

No GlobalLogic credential, endpoint, schema or authentication method was available to this proof of
concept, and **none was invented**. Where a real system could not be reached, the adapter, its
mapping, its tests and a clearly-labelled synthetic fixture exist, and this table records
\`SCHEMA DISCOVERED: NO\` for that row.

A fixture cannot reach \`REAL_VERIFIED\`. That status requires a live endpoint to have answered a
health check, and a fixture has no endpoint — so the value is unreachable in code, not merely
unclaimed (ADR-0037 §2).

**Column meanings.** *Schema discovered* is \`YES\` only where a live system's schema was actually
read. *Identity mapping* is how many projects have a **declared** mapping to that system; identity is
never resolved by name similarity, so an unmapped identifier quarantines rather than joining
(ADR-0035 §8). *Authority* is per canonical concept, never per system — see
\`SOURCE_AUTHORITY_MATRIX.md\`.`,
  )}
| Source | Business domain | Implementation | Real / fixture | Auth method | Schema discovered | Identity mapping | Concepts | Authority | Last sync | Volume | Data quality |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${connectorRows.join('\n')}

## Limitations, stated

- **No real enterprise system was contacted.** Six connector fixtures demonstrate the contract, the
  sync path, idempotency and drift detection against synthetic data shaped like their category.
- **Field names are generic to the category, not GlobalLogic's.** \`actual_cost\` is what a cost
  column is called in general. It is not a claim about any GlobalLogic tenant's schema.
- **The container is not deployed.** ADR-0032 §Verification: the target GCP project has billing
  disabled, and Cloud Run requires a billing-enabled project. The runtime builds, runs and is
  verified locally by \`npm run server:check\`; it is not running in a cloud environment.
`, 'utf8');

  // -------------------------------------------------------------------------
  // Source authority matrix (§104)
  // -------------------------------------------------------------------------
  const grants = [...demo.registry.authority.all()].sort(
    (a, b) => a.concept.localeCompare(b.concept) || a.priority - b.priority,
  );
  const authorityRows = grants.map((g) => `| \`${g.concept}\` | ${CONCEPT_LABEL[g.concept]} | ${g.sourceId} | **${g.authority}** | ${String(g.priority)} | ${g.conflictBehaviour} | ${g.rationale} |`);

  writeFileSync(join(DOCS, 'SOURCE_AUTHORITY_MATRIX.md'), `${HEADER(
    'Source authority matrix',
    `## POC configuration — not GlobalLogic policy

**No approved GlobalLogic data-ownership policy exists in this repository, and nothing below may be
represented as one.** These are the values this proof of concept configured, recorded here so that
changing one is a visible change to a governed artefact rather than an edit buried in a merge.

## Authority is per concept, not per system

A finance system is authoritative for actual cost and merely supplemental for delivery progress,
even though it stores a percentage. Declaring authority at system granularity would hand it both,
and the second one is wrong in a way that reaches a margin figure (ADR-0035 §3).

Where two sources disagree about the same project, the same concept and the same effective period,
the higher authority governs and the disagreement is **disclosed** rather than merged. There is no
\`OVERWRITE\` conflict behaviour, and a second \`AUTHORITATIVE\` grant for one concept at the same
priority is refused at registration rather than resolved at merge time.`,
  )}
| Concept | In business terms | Source | Authority | Priority | On conflict | Why |
| --- | --- | --- | --- | --- | --- | --- |
${authorityRows.join('\n')}

## Classes, highest first

| Class | Meaning |
| --- | --- |
| \`AUTHORITATIVE\` | The system of record. Its value is the governed value. |
| \`GOVERNED_REFERENCE\` | Holds the value of record for a concept another system originates. |
| \`SUPPLEMENTAL\` | Real, useful, and never the governed value. An uploaded extract is here. |
| \`EVIDENCE_ONLY\` | A document. Produces a quotation and a citation, never a value. |
| \`UNVERIFIED\` | Deny-by-default. A source with no registered grant for a concept has this. |
`, 'utf8');

  // -------------------------------------------------------------------------
  // Golden truth results (§105)
  // -------------------------------------------------------------------------
  const goldenRows: string[] = [];
  let passed = 0;
  for (const item of GOLDEN_TRUTH) {
    const answer = await askWithPlan(item.question, {
      ctx, tools, asOf: DEMO_NOW, scopeLabel: 'CDO', populationCount: authorised.length,
      vocabulary, knownMetricIds: [], state: NEW_CONVERSATION, knowledge: demo.registry,
    });
    const actual = readFact(answer, item);
    const ok = actual === item.expected;
    if (ok) passed += 1;
    goldenRows.push(
      `| ${item.question} | \`${item.claimId}\` | ${item.expected} | ${actual ?? '—'} | ${ok ? '**PASS**' : '**FAIL**'} |`,
    );
  }

  writeFileSync(join(DOCS, 'ASSISTANT_GOLDEN_TRUTH_RESULTS.md'), `${HEADER(
    'Assistant golden-truth results',
    `## What this compares, and what it does not

Facts, not prose. Each row asks a question through the full path — plan, validate, governed tools,
claims — and compares the **claim's own value** against the frozen baseline. Wording is free to
differ; a numeric or categorical mismatch is a P0.

The deterministic composer is used, so these results are reproducible and do not depend on a
credential being present. \`tests/integration/assistant-query-engine.test.ts\` asserts the same
figures, so a regression fails the build rather than only this document.

**Cross-provider equivalence** is asserted structurally rather than measured here: the model never
produces a figure. Claims are built before narration, the narration receives them as text, and the
grounding validator rejects any prose introducing a number the claims do not carry. A provider
therefore cannot change a fact — which is why switching one off leaves the answer intact and only
changes the \`composer\` badge.`,
  )}
| Question | Claim | Expected | Actual | Result |
| --- | --- | --- | --- | --- |
${goldenRows.join('\n')}

**${String(passed)} of ${String(GOLDEN_TRUTH.length)} golden-truth checks pass.**
`, 'utf8');

  // -------------------------------------------------------------------------
  // Ingestion validation results (§106)
  // -------------------------------------------------------------------------
  const verify = (id: string) => demo.registry.verify(id);
  const sow = verify('src-doc-atlas-sow');
  const upload = verify('src-upload-financials');
  const badVerify = verify('src-upload-bad');
  const minutesVerify = verify('src-doc-minutes');

  writeFileSync(join(DOCS, 'INGESTION_VALIDATION_RESULTS.md'), `${HEADER(
    'Ingestion validation results',
    `## "Learned" means three things, and they are reported separately

A source counts as grounded only when it is **ingested**, **retrievable**, *and* **demonstrably used
in an answer** (ADR-0036 §4). A successful upload satisfies the first and can fail the other two —
the common case being a document that is indexed and associated with no project, which no project
question will ever reach. Reporting one status would hide exactly that.

**No model weight is modified anywhere in this product.** What happens is ingestion, validation,
versioning, indexing, retrieval and citation. Every technical document in this repository uses those
words.`,
  )}
## PDF — a statement of work

| Property | Value |
| --- | --- |
| Fingerprint | \`${sowReceipt.receipt.fingerprint.slice(0, 32)}…\` |
| Pages parsed | ${String(sowReceipt.receipt.pagesParsed ?? 0)} |
| Chunks indexed | ${String(sowReceipt.receipt.chunksIndexed ?? 0)} |
| Parse completeness | ${sowReceipt.receipt.parseCompleteness ?? '—'} |
| Authority | ${sowReceipt.receipt.authority} |
| Data context | ${sowReceipt.receipt.dataContext} |
| Version | ${String(sowReceipt.version.versionOrdinal)} |
| Verification | ingested ${String(sow?.ingested)} · retrievable ${String(sow?.retrievable)} · used ${String(sow?.used)} → **${sow?.verdict ?? '—'}** |

Re-uploading identical bytes is admitted as \`DUPLICATE\`, not as a second version. Changed bytes
create a new version, and the previous one is retained so an answer that cited it still resolves.

## PDF — a document nobody associated with a project

| Property | Value |
| --- | --- |
| Pages parsed | ${String(minutes.receipt.pagesParsed ?? 0)} |
| Verification | ingested ${String(minutesVerify?.ingested)} · retrievable ${String(minutesVerify?.retrievable)} · used ${String(minutesVerify?.used)} → **${minutesVerify?.verdict ?? '—'}** |

Indexed and unreachable. This is the state a single "indexed" status would have concealed.

## XLSX — a supplemental financial extract

| Property | Value |
| --- | --- |
| Rows detected | ${String(supplemental.receipt.recordsDetected)} |
| Accepted | ${String(supplemental.receipt.recordsAccepted)} |
| Quarantined | ${String(supplemental.receipt.recordsQuarantined)} |
| Projects matched | ${String(supplemental.receipt.projectsMatched)} |
| Projects unresolved | ${String(supplemental.receipt.projectsUnresolved)} |
| Fields mapped / ignored | ${String(supplemental.receipt.fieldsMapped)} / ${String(supplemental.receipt.fieldsIgnored)} |
| Authority | ${supplemental.receipt.authority} |
| Data context | ${supplemental.receipt.dataContext} |
| Verification | **${upload?.verdict ?? '—'}** |

The unresolved row names a finance identifier with no **declared** identity mapping. It quarantines
rather than joining to a similarly-named project: two projects called "Atlas" in different accounts
is not an edge case, and a fuzzy join between them produces a cost figure that looks entirely
plausible.

## XLSX — deliberately bad rows

| Property | Value |
| --- | --- |
| Rows detected | ${String(bad.receipt.recordsDetected)} |
| Accepted | **${String(bad.receipt.recordsAccepted)}** |
| Quarantined | ${String(bad.receipt.recordsQuarantined)} |
| Verification | **${badVerify?.verdict ?? '—'}** |

Findings raised, each with a different human fix:

${[...new Set(bad.quarantined.flatMap((r) => r.findings.map((f) => f.code)))]
    .map((code) => `- \`${code}\``).join('\n')}

**Nothing changed.** \`tests/integration/knowledge-and-sources.test.ts\` asserts that the answer these
rows would have affected is byte-identical before and after, and that the registry holds zero
observations from them.

## Before / after

The same question — *"what does this project's SOW say about acceptance?"* — is \`NOT_ANSWERABLE\`
before the document is indexed and \`ANSWERABLE\` after, citing the document, its stated version and
the page. Asserted in \`tests/integration/knowledge-and-sources.test.ts\`; the page number is real
because the parser preserved pages, and a citation from a document whose pages could not be
established says *section*, never an inferred page.
`, 'utf8');

  process.stdout.write(
    `phase 13 evidence written: 4 documents · golden truth ${String(passed)}/${String(GOLDEN_TRUTH.length)}\n`,
  );
  if (passed !== GOLDEN_TRUTH.length) process.exit(1);
}

function readFact(
  answer: Awaited<ReturnType<typeof askWithPlan>>, item: GoldenCase,
): string | null {
  const claim = answer.response.materialClaims.find((c) => c.claimId === item.claimId);
  return claim?.display ?? null;
}

void main();
