/** Commercial, quality, resource and risk metric definitions. */
import { type MetricDefinition } from '../metric-types.js';
import { ALL_CONTRACT_TYPES, EDGE, FIXED_BID_ONLY, def } from './define.js';

const com = { sourceDomain: 'commercial', owner: 'Commercial', applicableContractTypes: ALL_CONTRACT_TYPES, status: 'Frozen', version: '1.0.0' } as const;
const qua = { sourceDomain: 'quality', owner: 'Engineering', applicableContractTypes: ALL_CONTRACT_TYPES, status: 'Frozen', version: '1.0.0' } as const;
const res = { sourceDomain: 'resource', owner: 'People', applicableContractTypes: ALL_CONTRACT_TYPES, status: 'Frozen', version: '1.0.0' } as const;
const rsk = { sourceDomain: 'risk', owner: 'Risk', applicableContractTypes: ALL_CONTRACT_TYPES, status: 'Frozen', version: '1.0.0' } as const;

export const COMMERCIAL_METRICS: readonly MetricDefinition[] = [
  def({ ...com, id: 'MET-COM-001', name: 'Invoiced to Date', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'FINANCE_SYSTEM',
    businessDefinition: 'Value invoiced to the customer to date. This is a billing figure and is not revenue.', formula: 'Σ Invoice.amount WHERE issuedAt ≤ t',
    inputs: ['commercial:Invoice.amount'], unit: 'Money', aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Invoice records'],
    notes: 'Decision 2D — do not call this recognised revenue. Billing follows contractual milestones; recognition follows accounting policy. They routinely differ.' }),
  def({ ...com, id: 'MET-COM-002', name: 'Collected to Date', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'FINANCE_SYSTEM',
    businessDefinition: 'Cash actually collected from the customer against issued invoices. This is a cash figure and is neither revenue nor billing.', formula: 'Σ Payment.amount WHERE receivedAt ≤ t',
    inputs: ['commercial:Payment.amount'], unit: 'Money', aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Payment records'],
    notes: 'Decision 2E — do not call this revenue. MET-COM-003 is the gap between this and billing.' }),
  def({ ...com, id: 'MET-COM-003', name: 'Receivables Outstanding', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Invoiced value the client has not yet paid.', formula: 'MET-COM-001 − MET-COM-002',
    inputs: ['MET-COM-001', 'MET-COM-002'], unit: 'Money', aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Invoice and payment records'] }),
  def({ ...com, id: 'MET-COM-004', name: 'Days Sales Outstanding', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How many days of billing are tied up in unpaid invoices.',
    formula: 'MET-COM-003 / (MET-COM-001 over trailing 90d / 90)',
    inputs: ['MET-COM-003', 'MET-COM-001'], unit: 'Days', aggregation: 'WEIGHTED_MEAN',
    currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.window(13), evidenceExpectations: ['Invoice and payment records'] }),
  def({ ...com, id: 'MET-COM-005', name: 'Aged Receivables > 60d', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Receivables outstanding more than 60 days.', formula: 'Σ Receivable.amount WHERE age > 60d',
    inputs: ['MET-COM-003'], unit: 'Money', aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Invoice records with due dates'] }),
  def({ ...com, id: 'MET-COM-006', name: 'Unbilled Revenue', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Revenue recognised but not yet invoiced.', formula: 'MET-FIN-009 − MET-COM-001',
    inputs: ['MET-FIN-009', 'MET-COM-001'], unit: 'Money', aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Finance recognised revenue record', 'Invoice records'],
    notes: 'The gap between what Finance has recognised and what has been billed. Both sides are Finance facts; this metric does not recompute either.' }),
  def({ ...com, id: 'MET-COM-007', name: 'Pending CR Ageing', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How long change requests have sat unexecuted. Long-ageing CRs are usually scope already delivered.',
    formula: 'max and mean of (t − raisedAt) over PendingChange WHERE NOT superseded',
    inputs: ['contract:PendingChange.raisedAt'], unit: 'Days', aggregation: 'MAX', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, applicableContractTypes: FIXED_BID_ONLY,
    evidenceExpectations: ['Pending change records with raise dates'],
    notes: 'Ageing survives execution because a pending change is never status-flipped in place (ADR-0003 §Decision 2).' }),
  def({ ...com, id: 'MET-COM-008', name: 'Scope Change Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How much the contracted scope has grown through executed changes.',
    formula: 'MET-FIN-002 / MET-FIN-001 − 1', inputs: ['MET-FIN-002', 'MET-FIN-001'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.ratio,
    baseline: 'AS_SOLD', evidenceExpectations: ['Executed change records'] }),
  def({ ...com, id: 'MET-COM-009', name: 'Uncompensated Scope Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The share of contract value being delivered as scope for which no change request has been executed.',
    formula: 'estimated value of delivered-but-uncontracted scope / MET-FIN-002',
    inputs: ['delivery:ScopeItem', 'contract:ExecutedChange', 'MET-FIN-002'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.ratio,
    applicableContractTypes: FIXED_BID_ONLY,
    evidenceExpectations: ['Scope items with no linked executed change', 'The estimation basis, labelled as an estimate'],
    notes: 'A signature Delivery Intelligence metric: work delivered without a CR is the most common silent margin killer in fixed-bid. Its input is an estimate and must be labelled as such.' }),
  def({ ...res, id: 'MET-RES-011', name: 'Resource Cost Drift Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Rate-and-mix cost drift as a share of budgeted cost, so the size of the drift is comparable across projects.',
    formula: 'abs(MET-RES-010) / MET-FIN-004',
    inputs: ['MET-RES-010', 'MET-FIN-004'], unit: 'Ratio',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    // Inherited from MET-RES-010: the drift being scaled is drift against the as-sold blended rate.
    baseline: 'AS_SOLD',
    evidenceExpectations: ['MET-RES-010 drift impact', 'MET-FIN-004 budgeted cost'],
    notes:
      'The comparand behind EW-RESOURCE-COST-DRIFT, which previously cited MET-RES-010 -- Money -- '
      + 'while comparing a ratio against 0.03 (DR-065). ABSOLUTE VALUE: the rule fires on drift in '
      + 'either direction, and the denominator is budgeted cost so an absolute dollar threshold does '
      + 'not fire on every large project and never on a small one.' }),
  def({ ...com, id: 'MET-COM-011', name: 'Liquidated Damages Exposure Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Live liquidated-damages exposure as a share of contract value.',
    formula: 'sum of CommercialExposure[kind = LIQUIDATED_DAMAGES].estimatedValue / MET-FIN-002',
    inputs: ['commercial:CommercialExposure', 'MET-FIN-002'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.ratio,
    applicableContractTypes: FIXED_BID_ONLY,
    evidenceExpectations: ['Liquidated-damages exposure records', 'The estimation basis, labelled as an estimate'],
    notes:
      'The comparand behind OVR-LD-EXPOSURE. Registered by ADR-0025: the hard override cited '
      + 'MET-FIN-019 (GM Value at Risk) as its signal metric, which is not what it compares, and the '
      + 'LD ratio itself had no registered metric -- so the override was declared, never assembled, '
      + 'and never evaluated on any project. Liquidated damages are a CONTRACTUAL remedy path: the '
      + 'exposure does not resolve through delivery recovery, which is why it forces RED in its own '
      + 'right rather than being absorbed into the weighted composite. Its input is an estimate and '
      + 'must be labelled as one.' }),
  def({ ...com, id: 'MET-COM-010', name: 'Expected Pending CR Recovery', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Probability-weighted value of pending change requests, used only for scenario analysis.',
    formula: 'Σ (PendingChange.proposedValue × PendingChange.approvalProbability)',
    inputs: ['contract:PendingChange.proposedValue', 'contract:PendingChange.approvalProbability'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    applicableContractTypes: FIXED_BID_ONLY, ruleSet: 'VAR-v1', calibrationParameters: [],
    evidenceExpectations: ['Pending change records', 'Probability assessment with assessor and date'],
    notes: 'Never base revenue (REQ-FIN-005). It enters MET-FIN-031 only, which is always displayed as a scenario.' }),
];

export const QUALITY_METRICS: readonly MetricDefinition[] = [
  def({ ...qua, id: 'MET-QUA-001', name: 'Open Defects by Severity', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'QUALITY_SYSTEM',
    businessDefinition: 'Count of unresolved defects, grouped by severity.', formula: 'count(Defect WHERE closedAt IS NULL) GROUP BY severity',
    inputs: ['quality:Defect'], unit: 'Count', aggregation: 'SUM', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Defect records'] }),
  def({ ...qua, id: 'MET-QUA-002', name: 'Defect Density', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Defects found per unit of scope delivered.', formula: 'defects found / scope units delivered',
    inputs: ['quality:Defect', 'delivery:ScopeItem'], unit: 'Ratio', aggregation: 'WEIGHTED_MEAN',
    currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio, status: 'Draft',
    evidenceExpectations: ['Defect records', 'Scope baseline'],
    notes: 'BLOCKED by MC-8 — **Type A**, inherited from the same undefined scope unit as MET-DEL-012. Owner: Delivery + Engineering. Removed from MET-HLTH-004 in Phase 2 closure and replaced by MET-QUA-010 acceptance blockers, so the quality health dimension is no longer blocked by it.' }),
  def({ ...qua, id: 'MET-QUA-003',
    version: '2.0.0', name: 'Escaped Defect Rate', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of defects found only after release to the client.',
    formula: 'count(Defect WHERE escapedToClient) / count(Defect)', inputs: ['quality:Defect'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Defect records with discovery phase'],
    notes:
      'ZERO-POPULATION SEMANTICS (ADR-0028): an empty defect population no longer means one thing. A REPORTING source with zero escaped defects is KNOWN_ZERO -- a healthy observation that scores. An ABSENT or STALE source is NOT_COMPUTABLE and costs the assessment its COMPLETE claim. Previously both were NOT_COMPUTABLE, the null was renormalised out of Product & Quality, and a dead telemetry feed read as excellent quality: Quality 41.67 -> 56.41, composite 68.38 -> 72.21, AMBER -> GREEN while still reporting COMPLETE.' }),
  def({ ...qua, id: 'MET-QUA-004', name: 'Defect Removal Efficiency', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of defects caught before release.',
    formula: 'pre-release defects / (pre + post-release defects)', inputs: ['quality:Defect'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Defect records with discovery phase'] }),
  def({ ...qua, id: 'MET-QUA-005', name: 'Mean Time to Resolve (S1/S2)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Average hours to close a critical or major defect.',
    formula: 'mean(closedAt − raisedAt) WHERE severity IN (CRITICAL, MAJOR)', inputs: ['quality:Defect'], unit: 'Hours',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Defect records with raise and closure timestamps'] }),
  def({ ...qua, id: 'MET-QUA-006', name: 'Rework Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of delivery effort spent redoing work rather than producing new scope.',
    formula: 'Σ EffortRecord.hours WHERE isRework / Σ EffortRecord.hours',
    inputs: ['resource:EffortRecord.hours'], unit: 'Percent', aggregation: 'WEIGHTED_MEAN',
    currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Effort records flagged as rework, with the defect or change that caused them'],
    notes: 'The primary bridge between engineering signals and the quality-rework cause in MET-FIN-018.' }),
  def({ ...qua, id: 'MET-QUA-012', name: 'Excess Rework Cost', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Cost of rework above the level assumed when the work was priced.',
    formula: '(MET-QUA-006 − baseline rework allowance) × MET-FIN-005',
    inputs: ['MET-QUA-006', 'MET-FIN-005', 'contract:baseline.reworkAllowance'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.ratio,
    baseline: 'AS_SOLD', evidenceExpectations: ['Rework effort records', 'Baseline rework allowance'],
    notes: 'The quality-rework cause in the margin bridge. Zero when rework is within the priced allowance.' }),
  def({ ...qua, id: 'MET-QUA-007', name: 'Automated Test Coverage', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'QUALITY_SYSTEM',
    businessDefinition: 'Automated test coverage as reported by the delivery team.', formula: 'QualitySnapshot.testCoverage',
    inputs: ['quality:QualitySnapshot.testCoverage'], unit: 'Percent', aggregation: 'WEIGHTED_MEAN',
    currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Coverage report reference'] }),
  def({ ...qua, id: 'MET-QUA-008', name: 'Change Failure Rate', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of releases that required remediation.',
    formula: 'failed changes / total changes in trailing 90d', inputs: ['quality:ReleaseRecord'], unit: 'Percent',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(13),
    evidenceExpectations: ['Release records with outcome'] }),
  def({ ...qua, id: 'MET-QUA-009', name: 'Defect Backlog Trend', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Whether the open-defect count is growing or shrinking.',
    formula: 'least-squares slope of MET-QUA-001 over trailing 8 weekly snapshots',
    inputs: ['MET-QUA-001'], unit: 'Count/period', aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.window(8), evidenceExpectations: ['Quality snapshots across the window'] }),
  def({ ...qua, id: 'MET-QUA-010', name: 'Acceptance Blockers', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'QUALITY_SYSTEM',
    businessDefinition: 'Open issues the client has named as preventing formal acceptance.',
    formula: 'count(AcceptanceItem WHERE blocking AND resolvedAt IS NULL)',
    inputs: ['quality:AcceptanceItem'], unit: 'Count', aggregation: 'SUM', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Acceptance items with client reference and raise date'],
    notes: 'Resolves MC-12. In fixed-bid these gate revenue, so they are an economic signal, not only a quality one.' }),
  def({ ...qua, id: 'MET-QUA-011', name: 'Acceptance Latency', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How long deliverables wait between submission and formal client acceptance.',
    formula: 'mean(acceptedAt − submittedAt) over AcceptanceItem WHERE accepted',
    inputs: ['quality:AcceptanceItem'], unit: 'Days', aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Acceptance items with submission and acceptance dates'],
    notes: 'Resolves MC-12. Rising latency with no rise in blockers usually indicates a client-side capacity problem, which is a dependency issue rather than a quality one.' }),
];

export const RESOURCE_METRICS: readonly MetricDefinition[] = [
  def({ ...res, id: 'MET-RES-001', name: 'Billable Utilisation', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of available hours booked to billable work.', formula: 'billable hours / available hours',
    inputs: ['resource:EffortRecord.hours'], unit: 'Percent', aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Effort records', 'Assignment availability'] }),
  def({ ...res, id: 'MET-RES-002', name: 'Effort Variance', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    version: '2.0.0',
    businessDefinition: 'Hours spent against the hours the work actually completed was priced at.',
    formula: 'actual hours − (contract:baseline.plannedEffortHours × physical completion at t)',
    inputs: ['resource:EffortRecord.hours', 'contract:baseline.plannedEffort', 'delivery:ProgressClaim.physicalCompletion'],
    unit: 'Hours', aggregation: 'SUM',
    currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator, baseline: 'CURRENT_CONTRACTUAL',
    evidenceExpectations: ['Effort records', 'Baseline effort plan', 'The claimed physical completion the baseline was time-phased by'],
    notes:
      'The named baseline is EARNED effort (ADR-0024). It must not be time-phased by planned ' +
      'completion: that asks whether the planned hours have been spent, so a late project books an ' +
      'effort saving for work it has not done. Positive is an overrun. Not computable where no ' +
      'progress has been claimed.' }),
  def({ ...res, id: 'MET-RES-003', name: 'Pyramid Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Ratio of senior to junior delivery staff.', formula: 'senior FTE / junior FTE (bands per resource config)',
    inputs: ['resource:Assignment'], unit: 'Ratio', aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Assignment records with seniority band'] }),
  def({ ...res, id: 'MET-RES-004', name: 'Pyramid Drift', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How far the delivered staffing shape has moved from what was priced.',
    formula: 'MET-RES-003 − as-sold pyramid ratio', inputs: ['MET-RES-003', 'contract:baseline.pyramidRatio'],
    unit: 'Ratio', aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    baseline: 'AS_SOLD', evidenceExpectations: ['Assignment records', 'As-sold staffing model'],
    notes: 'Quietly staffing seniors to hit a date is a canonical fixed-bid margin failure: delivery looks fine, margin does not.' }),
  def({ ...res, id: 'MET-RES-005', name: 'Blended Rate Variance', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Difference between the actual and as-sold average cost per delivery hour.',
    formula: 'actual blended cost rate − as-sold blended cost rate',
    inputs: ['resource:EffortRecord', 'financial:ActualCost', 'contract:baseline.blendedRate'], unit: 'Money/hr',
    aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.ratio,
    baseline: 'AS_SOLD', evidenceExpectations: ['Effort records', 'Cost ledger', 'As-sold rate card'] }),
  def({ ...res, id: 'MET-RES-010', name: 'Resource Cost Drift Impact', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The margin impact of paying more per delivery hour than was priced.',
    formula: 'MET-RES-005 × total delivery hours to date',
    inputs: ['MET-RES-005', 'resource:EffortRecord.hours'], unit: 'Money', aggregation: 'SUM',
    currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator, baseline: 'AS_SOLD',
    evidenceExpectations: ['Blended rate variance derivation', 'Effort records'],
    notes: 'The rate/mix cause in the margin bridge.' }),
  def({ ...res, id: 'MET-RES-006', name: 'Attrition Rate (rolling 12m)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of the team that has left over the last twelve months.', formula: 'leavers / mean headcount',
    inputs: ['resource:Assignment'], unit: 'Percent', aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.window(52), evidenceExpectations: ['Assignment start and end records'] }),
  def({ ...res, id: 'MET-RES-007', name: 'Key Person Concentration', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of critical-path effort delivered by the two largest individual contributors.',
    formula: '% of critical-path effort delivered by top 2 individuals', inputs: ['resource:EffortRecord'],
    unit: 'Percent', aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Effort records by individual, aggregated'],
    notes: 'Reports a percentage, never a name. Identity is PERSONAL_DATA and is gated separately (SECURITY_MODEL.md §8).' }),
  def({ ...res, id: 'MET-RES-008', name: 'Ramp Deficit', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Shortfall between planned and actual staffing at the as-of date.', formula: 'planned FTE@t − actual FTE@t',
    inputs: ['resource:Assignment', 'contract:baseline.staffingCurve'], unit: 'FTE', aggregation: 'SUM',
    currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator, baseline: 'CURRENT_CONTRACTUAL',
    evidenceExpectations: ['Assignment records', 'Baseline staffing curve'] }),
  def({ ...res, id: 'MET-RES-009', name: 'Open Role Ageing', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Average days that unfilled roles have been open.', formula: 'mean(t − openedAt) over unfilled roles',
    inputs: ['resource:OpenRole'], unit: 'Days', aggregation: 'MAX', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Open role records'] }),
];

export const RISK_METRICS: readonly MetricDefinition[] = [
  def({ ...rsk, id: 'MET-RSK-001', name: 'Risk Exposure (gross)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Probability-weighted financial impact of all open risks, before considering what is already provisioned.',
    formula: 'Σ (Risk.probability × Risk.costImpact) over open risks',
    inputs: ['risk:Risk.probability', 'risk:Risk.costImpact'], unit: 'Money', aggregation: 'SUM',
    currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    evidenceExpectations: ['Risk register entries with probability and impact, and who assessed them'] }),
  def({ ...rsk, id: 'MET-RSK-008', name: 'Incremental Risk Exposure', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Probability-weighted impact of risks that are not already provisioned inside the estimate to complete.',
    formula: 'Σ (Risk.probability × Risk.costImpact) over open risks WHERE NOT includedInEtc',
    inputs: ['risk:Risk.probability', 'risk:Risk.costImpact', 'risk:Risk.includedInEtc'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator, ruleSet: 'VAR-v1', calibrationParameters: [],
    evidenceExpectations: ['Risk register entries with the IncludedInETC flag and its justification'],
    notes: 'The flag is what prevents double counting. A risk provisioned inside ETC and also deducted from margin is counted twice, which systematically understates the portfolio.' }),
  def({ ...rsk, id: 'MET-RSK-002', name: 'Open Critical Risks', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'DELIVERY_SYSTEM',
    businessDefinition: 'Number of open risks rated critical.', formula: 'count(Risk WHERE severity = CRITICAL AND state = OPEN)',
    inputs: ['risk:Risk'], unit: 'Count', aggregation: 'SUM', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Risk register entries'] }),
  def({ ...rsk, id: 'MET-RSK-003', name: 'Risk Proximity', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Days until the nearest critical risk could materialise.', formula: 'min(Risk.proximityDate) − t WHERE severity = CRITICAL',
    inputs: ['risk:Risk.proximityDate'], unit: 'Days', aggregation: 'MIN', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Risk register entries with proximity windows'] }),
  def({ ...rsk, id: 'MET-RSK-004', name: 'Mitigation Coverage', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Share of open risks that have an owned, in-date mitigation.',
    formula: 'risks with an owned in-date mitigation / open risks', inputs: ['risk:Risk', 'risk:Mitigation'],
    unit: 'Percent', aggregation: 'WEIGHTED_MEAN', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Mitigation records with owner and due date'] }),
  def({ ...rsk, id: 'MET-RSK-005', name: 'Overdue Mitigations', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Number of mitigations past their due date.', formula: 'count(Mitigation WHERE dueDate < t AND NOT complete)',
    inputs: ['risk:Mitigation'], unit: 'Count', aggregation: 'SUM', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.noDenominator, evidenceExpectations: ['Mitigation records'] }),
  def({ ...rsk, id: 'MET-RSK-006', name: 'Risk Register Freshness', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Days since the risk register was last updated.', formula: 't − max(Risk.updatedAt)',
    inputs: ['risk:Risk.updatedAt'], unit: 'Days', aggregation: 'MAX', currencyBehaviour: 'NONE',
    edgeHandling: EDGE.ratio, evidenceExpectations: ['Risk register update timestamps'] }),
  def({ ...rsk, id: 'MET-RSK-007', name: 'Issue Escalation Rate', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How many risks have become live issues recently.',
    formula: 'count(Risk WHERE state transitioned to REALISED in trailing 90d)', inputs: ['risk:Risk.state'],
    unit: 'Count', aggregation: 'SUM', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(13),
    evidenceExpectations: ['Risk state transition records'] }),
];
