/** Delivery and earned-value metric definitions — owned by the `delivery` context. */
import { type MetricDefinition } from '../metric-types.js';
import { ALL_CONTRACT_TYPES, EDGE, FIXED_BID_ONLY, def } from './define.js';

const base = {
  sourceDomain: 'delivery', owner: 'Delivery', applicableContractTypes: ALL_CONTRACT_TYPES,
  status: 'Frozen', version: '1.0.0',
} as const;

export const DELIVERY_METRICS: readonly MetricDefinition[] = [
  def({ ...base, id: 'MET-DEL-016', name: 'Actual Physical Completion', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'MANUAL_DECLARATION',
    businessDefinition: 'The proportion of contracted scope the delivery team asserts is genuinely finished, assessed against defined completion criteria — not effort spent.',
    formula: 'ProgressClaim.physicalCompletion (latest ≤ t)',
    inputs: ['delivery:ProgressClaim.physicalCompletion'], unit: 'Percent',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    evidenceExpectations: ['Progress claim with assessor, date, and completion-criteria basis'],
    notes: 'An observed fact — a recorded assertion — not a derived value. Its reliability is measured by MET-FIN-027 and MET-FIN-030, not assumed. Distinct from MET-DEL-012, which counts scope units and is blocked by MC-8.' }),
  def({ ...base, id: 'MET-DEL-017', name: 'Planned Physical Completion', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The proportion of scope the baseline schedule says should be complete by now.',
    formula: 'baseline.plannedProgressCurve@t (named baseline)',
    inputs: ['contract:baseline.plannedProgressCurve'], unit: 'Percent',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Baseline progress curve'],
    notes:
      'The "named baseline" defers nothing here: it is the contract baseline progress curve, a ' +
      'single observed series on the current contractual baseline, so there is exactly one reading. ' +
      'Recorded explicitly because the identical phrasing in MET-RES-002 DID defer a choice, and ' +
      'the implementation named the wrong field (ADR-0024). MET-DEL-017 is PLANNED progress; ' +
      'MET-DEL-016 is CLAIMED physical progress. They differ on 74 of 75 fixed-bid projects and are ' +
      'not interchangeable: time-phasing effort by this metric credits unperformed work as a saving.' }),
  def({ ...base, id: 'MET-DEL-015', name: 'Progress Variance', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How far actual delivered progress is ahead of or behind the plan. Negative means behind.',
    formula: 'MET-DEL-016 − MET-DEL-017',
    inputs: ['MET-DEL-016', 'MET-DEL-017'], unit: 'PercentagePoints',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Progress claim', 'Baseline progress curve'] }),
  def({ ...base, id: 'MET-DEL-019', name: 'Demonstrated Velocity', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The rate of progress the project has actually achieved over the recent past.',
    formula: '(MET-DEL-016@t − MET-DEL-016@t−8w) / 8',
    inputs: ['MET-DEL-016'], unit: 'Percent',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(8),
    evidenceExpectations: ['Progress claims across the trailing window'] }),
  def({ ...base, id: 'MET-DEL-020', name: 'Required Future Velocity', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The rate of progress needed from now on to finish by the committed date.',
    formula: '(100% − MET-DEL-016) / weeks remaining to baseline completion',
    inputs: ['MET-DEL-016', 'contract:baseline.completionDate'], unit: 'Percent',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Progress claim', 'Baseline completion date'] }),
  def({ ...base, id: 'MET-DEL-018',
    version: '2.0.0', name: 'Required Velocity Ratio', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How many times faster the project must run from here than it has run so far.',
    formula: 'MET-DEL-020 / MET-DEL-019',
    inputs: ['MET-DEL-020', 'MET-DEL-019'], unit: 'Ratio',
    aggregation: 'MAX', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(8),
    evidenceExpectations: ['Both velocity derivations'],
    notes:
      'ZERO-DENOMINATOR SEMANTICS (ADR-0027): an UNKNOWN demonstrated velocity is NOT_COMPUTABLE, but an OBSERVED zero with positive required velocity is UNBOUNDED -- an adverse observation, not missing evidence. UNBOUNDED breaches any finite upper threshold and scores at the red edge; it is never dropped from a dimension. No Infinity is produced: the numeric value stays null and the state is carried explicitly. Observed zero with ZERO required velocity is benign and reported as not computable. A ratio above roughly 1.5 sustained over weeks is the clearest available evidence that a recovery plan is arithmetic rather than a plan.' }),
  def({ ...base, id: 'MET-DEL-021', name: 'Required Productivity Improvement %', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'The productivity uplift the remaining plan silently assumes.',
    formula: 'MET-DEL-018 − 1',
    inputs: ['MET-DEL-018'], unit: 'Percent',
    aggregation: 'MAX', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(8),
    evidenceExpectations: ['Required velocity ratio derivation'] }),
  def({ ...base, id: 'MET-DEL-001', name: 'Planned Value (PV)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Budgeted cost of the work the baseline says should have been done by now.',
    formula: 'baseline.plannedCostCurve@t',
    inputs: ['contract:baseline.plannedCostCurve'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Baseline cost curve'] }),
  def({ ...base, id: 'MET-DEL-002', name: 'Earned Value (EV)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Budgeted cost of the work actually completed.',
    formula: 'MET-FIN-004 × MET-DEL-016',
    inputs: ['MET-FIN-004', 'MET-DEL-016'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Contractual cost baseline', 'Progress claim'],
    notes: 'Uses physical completion (MET-DEL-016) rather than scope units, so it is not blocked by MC-8.' }),
  def({ ...base, id: 'MET-DEL-003', name: 'Actual Cost (AC)', epistemicLevel: 'L1_OBSERVED', authoritativeSourceType: 'FINANCE_SYSTEM',
    businessDefinition: 'Delivery cost incurred to date, presented in earned-value terms.',
    formula: 'MET-FIN-005',
    inputs: ['MET-FIN-005'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    evidenceExpectations: ['Cost ledger'],
    notes: 'An alias, not a second definition. `financial` owns the computation; `delivery` consumes it.' }),
  def({ ...base, id: 'MET-DEL-004', name: 'Cost Performance Index (CPI)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Value earned per unit of cost spent. Below 1.0 means work is costing more than budgeted.',
    formula: 'MET-DEL-002 / MET-DEL-003',
    inputs: ['MET-DEL-002', 'MET-DEL-003'], unit: 'Index',
    aggregation: 'RECOMPUTE_FROM_INPUTS', currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['EV and AC derivations'] }),
  def({ ...base, id: 'MET-DEL-005', name: 'Schedule Performance Index (SPI)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Value earned against value planned. Below 1.0 means the project is behind schedule.',
    formula: 'MET-DEL-002 / MET-DEL-001',
    inputs: ['MET-DEL-002', 'MET-DEL-001'], unit: 'Index',
    aggregation: 'RECOMPUTE_FROM_INPUTS', currencyBehaviour: 'SINGLE_CURRENCY', edgeHandling: EDGE.ratio,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['EV and PV derivations'] }),
  def({ ...base, id: 'MET-DEL-006', name: 'Cost Variance (EVM)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Value earned minus cost spent, in currency.',
    formula: 'MET-DEL-002 − MET-DEL-003',
    inputs: ['MET-DEL-002', 'MET-DEL-003'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['EV and AC derivations'] }),
  def({ ...base, id: 'MET-DEL-007', name: 'Schedule Variance (EVM)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Value earned minus value planned, in currency.',
    formula: 'MET-DEL-002 − MET-DEL-001',
    inputs: ['MET-DEL-002', 'MET-DEL-001'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['EV and PV derivations'] }),
  def({ ...base, id: 'MET-DEL-008', name: 'Variance at Completion (VAC)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Expected cost overrun or underrun against the contractual budget at completion.',
    formula: 'MET-FIN-004 − MET-FIN-008',
    inputs: ['MET-FIN-004', 'MET-FIN-008'], unit: 'Money',
    aggregation: 'SUM', currencyBehaviour: 'FX_CONVERT_REQUIRED', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Contractual cost baseline', 'EAC components'] }),
  def({ ...base, id: 'MET-DEL-009', name: 'Milestone Slippage', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Total days of delay across milestones against a named baseline.',
    formula: 'Σ max(0, forecastDate − baselineDate) over milestones',
    inputs: ['delivery:Milestone.baselineDate', 'delivery:Milestone.forecastDate'], unit: 'Days',
    aggregation: 'SUM', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Milestone records with both dates'] }),
  def({ ...base, id: 'MET-DEL-010', name: 'Milestones At Risk', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How many milestones are currently forecast to miss their baseline date.',
    formula: 'count(Milestone WHERE forecastDate > baselineDate AND actualDate IS NULL)',
    inputs: ['delivery:Milestone'], unit: 'Count',
    aggregation: 'SUM', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Milestone records'] }),
  def({ ...base, id: 'MET-DEL-011', name: 'Schedule Variance (calendar)', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Days between forecast and baseline completion of the project as a whole.',
    formula: 'forecastCompletionDate − baselineCompletionDate',
    inputs: ['delivery:forecastCompletionDate', 'contract:baseline.completionDate'], unit: 'Days',
    aggregation: 'MAX', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    baseline: 'CURRENT_CONTRACTUAL', evidenceExpectations: ['Forecast and baseline completion dates'] }),
  def({ ...base, id: 'MET-DEL-012', name: 'Scope Completion', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Proportion of contracted scope units delivered.',
    formula: 'completed scope units / total scope units (named baseline)',
    inputs: ['delivery:ScopeItem'], unit: 'Percent',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    baseline: 'CURRENT_CONTRACTUAL', status: 'Draft',
    evidenceExpectations: ['Scope baseline', 'Scope item completion records'],
    notes: 'BLOCKED by MC-8 — **Type A**. What a "scope unit" is (a requirement? a story? a deliverable?) is undefined, and the answer changes what the number means: two projects counted in different units are not comparable. This is a semantic gap, not a threshold awaiting a value, so the metric cannot be frozen. Owner: Delivery + Phase 2 metric owner. Nothing downstream is blocked — MET-DEL-016 physical completion carries progress everywhere it is needed.' }),
  def({ ...base, id: 'MET-DEL-013', name: 'Velocity Stability', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How consistent the delivery rate has been. High variability makes any forecast unreliable.',
    formula: 'stddev(weekly ΔMET-DEL-016 over trailing 6) / mean(same)',
    inputs: ['MET-DEL-016'], unit: 'Ratio',
    aggregation: 'NOT_AGGREGATABLE', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(6),
    evidenceExpectations: ['Progress claims across the trailing window'] }),
  def({ ...base, id: 'MET-DEL-014', name: 'Replan Frequency', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How often the forecast baseline has been revised recently.',
    formula: 'count(BaselineRevision WHERE kind = FORECAST AND date ≥ t − 90d)',
    inputs: ['contract:BaselineRevision'], unit: 'Count',
    aggregation: 'SUM', currencyBehaviour: 'NONE', edgeHandling: EDGE.window(13),
    evidenceExpectations: ['Baseline revision records with actor and reason'],
    notes: 'A governance signal, not a delivery signal: frequent revision is often the visible residue of a project rebasing its way out of visible variance.' }),
  def({ ...base, id: 'MET-DEL-022', name: 'Blocked Effort', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'Delivery effort unable to proceed because of an unmet customer or third-party dependency.',
    formula: 'Σ EffortRecord.hours WHERE blockedByDependencyId IS NOT NULL',
    inputs: ['resource:EffortRecord.hours', 'delivery:Dependency'], unit: 'Hours',
    aggregation: 'SUM', currencyBehaviour: 'NONE', edgeHandling: EDGE.noDenominator,
    evidenceExpectations: ['Dependency records with owner and due date', 'Effort records referencing them'],
    notes: 'In fixed-bid, blocked effort is usually cost we absorb and a commercial claim we do not make. It is the L1 fact behind the customer-dependency cause in MET-FIN-018.' }),
  def({ ...base, id: 'MET-DEL-023', name: 'Customer Dependency Ageing', epistemicLevel: 'L2_DERIVED', authoritativeSourceType: 'DERIVED',
    businessDefinition: 'How long unmet customer dependencies have been outstanding.',
    formula: 'max and mean of (t − raisedDate) over open Dependency WHERE owner = CUSTOMER',
    inputs: ['delivery:Dependency'], unit: 'Days',
    aggregation: 'MAX', currencyBehaviour: 'NONE', edgeHandling: EDGE.ratio,
    evidenceExpectations: ['Dependency records with raise dates and owners'] }),
];
